name: Build

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo build -r
        mkdir -p ./build/release
        cp ./target/release/rumo ./build/release/rumo
        cd ./build/release
        shasum -a 256 rumo > rumo.sha256
    
    - name: Upload Github Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: build/release/*
        prerelease: ${{ contains(github.ref, '-') }}
