name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:db.sqlite3?mode=rwc
      SECRET_KEY: fake-key
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Init
      run: cargo run -- init
    - name: Run tests
      run: cargo test --verbose
